INSERT INTO airport (id, name, city, country) VALUES
  ('BVA', 'Beauvais-Tillé Airport', 'Paris', 'France'),
  ('BRU', 'Brussels Airport', 'Brussels', 'Belgium'),
  ('CRL', 'Brussels South Charleroi Airport', 'Brussels', 'Belgium'),
  ('OPO', 'Francisco Sa Carneiro Airport', 'Paris', 'France'),
  ('VNO', 'Vilnius Airport', 'Vilnius', 'Lithuania'),
  ('BCN', 'Barcelona Airport', 'Barcelona', 'Spain'),
  ('WAW', 'Warsaw Chopin Airport', 'Warsaw', 'Poland'),
  ('KRA', 'John Paul II Airport ', 'Krakow','Poland'),
  ('CPH', 'Copenhagen Airport', 'Copenhagen', 'Denmark'),
  ('CIA', 'Rome Ciampino Airport', 'Rome', 'Italy'),
  ('FCO', 'Leonardo da Vinci-Fiumicino Airport', 'Rome', 'Italy'),
  ('STN', 'Stansted Airport',        'London', 'United Kingdom'),
  ('LTN', 'Luton Airport',           'Luton', 'United Kingdom' ),
  ('OSL', 'Oslo Airport-Gardermoen', 'Oslo', 'Sweden');
